### ISSUE TITLE
How about writing SlcanBridge class in the header for manual composition?

### ISSUE THREAD

**Issue by Stew-000-1-0-011** [IndigoCarmine/can_plugins2#6]
Now I'm using English Keyboard. I cannot write Japanese characters.
By the way, what do you think about writing node class on header file?
It is very useful for manual composition, and other style in which dependencies explicitly appear.

**Comment by IndigoCarmine** [comment]
As this is the recommended method in ROS2, I think it needs to be addressed. However, this is not possible now, so please submit a pull request or wait me.

**Comment by IndigoCarmine** [comment]
It might be supported. I will close the issue.
